name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://www.coolapk.com/link?url=https%3A%2F%2Fdownload.meizu.com%2FFirmware%2FFlyme%2F16s%2F9.21.6.29%2Fcn_beta%2F20210629140442%2F243f074d%2Fupdate.zip
  OS_TYPE: Flyme  #  Flyme  GenericI   MIUI   OxygenOS  Pixel
  REPACK_NAME: GSI_by-jczhl
  make_type: ab     #aonly    ab
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: 获取本仓库源码
         uses: actions/checkout@master
         
       - name: 清理环境
         run: |
           docker rmi `docker images -q`
           
       - name: 下载 ErfanGSIs 工具
         run: |
            git clone --recurse-submodules https://github.com/zhl/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
            curl -sL https://git.io/file-transfer | sh
             
       - name: 配置环境
         run: |
           mkdir zhlhlf
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: 下载ROM & 并生成GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $OS_TYPE --$make_type
           ls /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/

#       - name: 7z打包GSI镜像
 #        run: |
  #          7z a -r $OS_TYPE-$REPACK_NAME-$make_type.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*
            
       - name: zip 打包
         run: |
           zip -r $OS_TYPE-$REPACK_NAME-$make_type.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*
           ls
           if [[ $(du -sb $OS_TYPE-$REPACK_NAME-$make_type.zip | awk '{print $1}') -gt 2097152000 ]];then
                 echo -e "split packaging..."
                 tar -cpzf - $OS_TYPE-$REPACK_NAME-$make_type.zip | split -d -b 1024m - upload/$OS_TYPE-$REPACK_NAME-$make_type.zip
             fi

       - name: 移动生成包至zhlhlf目录
         run: |
          mv $OS_TYPE-$REPACK_NAME-$make_type.* zhlhlf
                              
       - name: 上传zhlhlf目录所有文件至WeTransfer
         run: |
            sudo ./transfer wet zhlhlf/*

#       - name: 上传zhlhlf目录所有文件至 release
 #        uses: ncipollo/release-action@v1.8.6
  #       with:
   #        artifacts: zhlhlf/*
    #       name: SGSI-ab-Android10
     #      tag: SGSI-ab-Android10-${{ github.run_number }}
      #     token: ${{ secrets.GITHUB_TOKEN }}

