name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://bigota.d.miui.com/V12.5.1.0.QEECNXM/miui_MIMIX3_V12.5.1.0.QEECNXM_b008b041ef_10.0.zip
  ROM_NAME: MIUI  #  Flyme  GenericI   MIUI   OxygenOS  Pixel
  REPACK_NAME: GSI_by-jczhl
  make_type: ab     #aonly    ab
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: 清理环境
         run: |
           docker rmi `docker images -q`
           
       - name: 下载 ErfanGSIs 工具
         run: |
            git clone --recurse-submodules https://github.com/jczhl/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
            curl -sL https://git.io/file-transfer | sh
             
       - name: 配置环境
         run: |
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: 下载ROM & 并生成GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME --$make_type
           ls /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/

       - name: 7z打包GSI镜像
         run: |
            7z a -r $ROM_NAME-$REPACK_NAME-$make_type.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*
          
       - name: 上传7z压缩包至WeTransfer
         run: |
            sudo ./transfer wet $ROM_NAME-$REPACK_NAME-$make_type.7z
