name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://www.coolapk.com/link?url=https%3A%2F%2Fdownload.meizu.com%2FFirmware%2FFlyme%2F16th%2F9.21.6.29%2Fcn_beta%2F20210629122654%2F0197229f%2Fupdate.zip
  ROM_NAME: Flyme
  REPACK_NAME: GSI_by-jczhl
  make_type: ab     #aonly    ab
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Cleaning up
         run: |
           docker rmi `docker images -q`
       - name: Cloning ErfanGSIs tools
         run: |
            git clone --recurse-submodules https://github.com/zhlhlf/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
            curl -sL https://git.io/file-transfer | sh
             
       - name: Setting up Porting Environment
         run: |
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME --$make_type
           ls /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/

       - name: Packing Output File to 7z
         run: |
            7z a -r $ROM_NAME-$REPACK_NAME-$make_type.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*
          
       - name: Uploading SGSI to WeTransfer
         run: |
            sudo ./transfer wet $ROM_NAME-$REPACK_NAME-$make_type.7z
